apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: devboard
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: DevBoard - K8s learning project

  sourceRepos:
    - "*"  # In production, restrict to your actual repo URL

  destinations:
    - namespace: devboard
      server: https://kubernetes.default.svc
    - namespace: monitoring
      server: https://kubernetes.default.svc
    - namespace: logging
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: "*"
      kind: "*"

  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
