replicaCount: 1
image:
  repository: ghcr.io/mitsu3s/devboard-activity-service
  pullPolicy: IfNotPresent
  tag: "924355bae5e43cb22d838efd36ad16a95151bbaf"
service:
  type: ClusterIP
  port: 8080
env:
  MYSQL_DSN: "devboard:devboard123@tcp(mysql:3306)/devboard?charset=utf8mb4&parseTime=True&loc=Local"
  ACCESS_SERVICE_URL: "http://access-service:8080"
  RABBITMQ_URL: "amqp://devboard:devboard123@rabbitmq:5672/"
  OTEL_SERVICE_NAME: "activity-service"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.monitoring.svc.cluster.local:4318"
  OTEL_TRACES_EXPORTER: "otlp"
  OTEL_TRACES_SAMPLER: "parentbased_traceidratio"
  OTEL_TRACES_SAMPLER_ARG: "1.0"
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 192Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
serviceMonitor:
  enabled: true
  interval: 15s
