apiVersion: v1
kind: Service
metadata:
  name: {{ include "workflow-service.fullname" . }}
  labels:
    {{- include "workflow-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "workflow-service.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
{{- if .Values.serviceMonitor.enabled }}
    - name: http-envoy-prom
      port: 15020
      targetPort: 15020
      protocol: TCP
{{- end }}
