replicaCount: 1
image:
  repository: ghcr.io/mitsu3s/devboard-notification-service
  pullPolicy: IfNotPresent
  tag: "d521070554873e772ffc061ae67019dd04ee2379"
service:
  type: ClusterIP
  port: 8080
env:
  RABBITMQ_URL: "amqp://devboard:devboard123@rabbitmq:5672/"
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 192Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
serviceMonitor:
  enabled: true
  interval: 15s
