replicaCount: 1
image:
  repository: ghcr.io/mitsu3s/devboard-notification-service
  pullPolicy: IfNotPresent
  tag: "d13358cd723793cb60f97fee55e7092dac9a47f8"
service:
  type: ClusterIP
  port: 8080
env:
  REDIS_ADDR: "redis:6379"
resources:
  requests:
    cpu: 50m
    memory: 32Mi
  limits:
    cpu: 200m
    memory: 128Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
serviceMonitor:
  enabled: true
  interval: 15s
