replicaCount: 1
image:
  repository: ghcr.io/mitsu3s/devboard-search-service
  pullPolicy: IfNotPresent
  tag: "bfb5ad3b96c67bb4ca59d434a9f8c00cd0f9572f"
service:
  type: ClusterIP
  port: 8080
env:
  RABBITMQ_URL: "amqp://devboard:devboard123@rabbitmq:5672/"
  ACCESS_SERVICE_URL: "http://access-service:8080"
  ELASTICSEARCH_URL: "https://elasticsearch-es-http.logging.svc:9200"
  ELASTICSEARCH_USERNAME: "elastic"
  ELASTICSEARCH_CA_CERT_PATH: "/etc/elasticsearch/certs/tls.crt"
  TASKS_INDEX_NAME: "devboard-tasks"
elasticsearch:
  passwordSecret:
    name: search-service-elasticsearch-credentials
    key: password
  caSecret:
    name: search-service-elasticsearch-ca
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 300m
    memory: 256Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
serviceMonitor:
  enabled: true
  interval: 15s
