replicaCount: 1
image:
  repository: ghcr.io/mitsu3s/devboard-search-service
  pullPolicy: IfNotPresent
  tag: "ec49e5c2a664c7ea2fb977ec8395abbd8f89538f"
service:
  type: ClusterIP
  port: 8080
env:
  RABBITMQ_URL: "amqp://devboard:devboard123@rabbitmq.devboard.svc.cluster.local:5672/"
  ACCESS_SERVICE_URL: "http://access-service.devboard.svc.cluster.local:8080"
  ELASTICSEARCH_URL: "https://elasticsearch-es-http.logging.svc.cluster.local:9200"
  ELASTICSEARCH_USERNAME: "elastic"
  ELASTICSEARCH_CA_CERT_PATH: "/etc/elasticsearch/certs/tls.crt"
  TASKS_INDEX_NAME: "devboard-tasks"
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 300m
    memory: 256Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
serviceMonitor:
  enabled: true
  interval: 15s
