{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "web-bff.fullname" . }}
  labels:
    {{- include "web-bff.labels" . | nindent 4 }}
    # This label is required by kube-prometheus-stack to auto-discover monitors
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      {{- include "web-bff.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
