replicaCount: 1
image:
  repository: ghcr.io/mitsu3s/devboard-access-service
  pullPolicy: IfNotPresent
  tag: "b3d31a9679de77e6dba5923f2b01cff267ee001d"
service:
  type: ClusterIP
  port: 8080
env:
  MEMBERSHIP_SERVICE_URL: "http://membership-service:8080"
  BOARD_QUERY_SERVICE_URL: "http://board-query-service:8080"
  OTEL_SERVICE_NAME: "access-service"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.monitoring.svc.cluster.local:4318"
  OTEL_TRACES_EXPORTER: "otlp"
  OTEL_TRACES_SAMPLER: "parentbased_traceidratio"
  OTEL_TRACES_SAMPLER_ARG: "1.0"
resources:
  requests:
    cpu: 50m
    memory: 32Mi
  limits:
    cpu: 300m
    memory: 128Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
serviceMonitor:
  enabled: true
  interval: 15s
