{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "board-query-service.fullname" . }}
  labels:
    {{- include "board-query-service.labels" . | nindent 4 }}
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      {{- include "board-query-service.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http-envoy-prom
      path: /stats/prometheus
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
