replicaCount: 1
image:
  repository: ghcr.io/mitsu3s/devboard-task-command-service
  pullPolicy: IfNotPresent
  tag: "e8258a6a5beee4fc9c80ebe77f545722c61985b9"
service:
  type: ClusterIP
  port: 8080
env:
  MYSQL_DSN: "devboard:devboard123@tcp(mysql:3306)/devboard?charset=utf8mb4&parseTime=True&loc=Local"
  RABBITMQ_URL: "amqp://devboard:devboard123@rabbitmq:5672/"
  OTEL_SERVICE_NAME: "task-command-service"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.monitoring.svc.cluster.local:4318"
  OTEL_TRACES_EXPORTER: "otlp"
  OTEL_TRACES_SAMPLER: "parentbased_traceidratio"
  OTEL_TRACES_SAMPLER_ARG: "1.0"
resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 256Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
serviceMonitor:
  enabled: true
  interval: 15s
