apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: search-service-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: devboard
  source:
    repoURL: https://github.com/mitsu3s/web-service
    targetRevision: HEAD
    path: k8s/search-service-secrets
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: devboard
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - SkipDryRunOnMissingResource=true
