replicaCount: 1
image:
  repository: ghcr.io/mitsu3s/devboard-task-orchestrator-service
  pullPolicy: IfNotPresent
  tag: "ec49e5c2a664c7ea2fb977ec8395abbd8f89538f"
service:
  type: ClusterIP
  port: 8080
env:
  ACCESS_SERVICE_URL: "http://access-service:8080"
  WORKFLOW_SERVICE_URL: "http://workflow-service:8080"
  TASK_COMMAND_SERVICE_URL: "http://task-command-service:8080"
  OTEL_SERVICE_NAME: "task-orchestrator-service"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.monitoring.svc.cluster.local:4318"
  OTEL_TRACES_EXPORTER: "otlp"
  OTEL_TRACES_SAMPLER: "parentbased_traceidratio"
  OTEL_TRACES_SAMPLER_ARG: "1.0"
resources:
  requests:
    cpu: 50m
    memory: 32Mi
  limits:
    cpu: 300m
    memory: 128Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
serviceMonitor:
  enabled: true
  interval: 15s
