replicaCount: 1
image:
  repository: ghcr.io/mitsu3s/devboard-search-indexer
  pullPolicy: IfNotPresent
  tag: "99137ee45e2619930b757b8b06f2717d6551988d"
service:
  type: ClusterIP
  port: 8080
env:
  RABBITMQ_URL: "amqp://devboard:devboard123@rabbitmq.devboard.svc.cluster.local:5672/"
  ELASTICSEARCH_URL: "https://elasticsearch-es-http.logging.svc.cluster.local:9200"
  ELASTICSEARCH_USERNAME: "elastic"
  ELASTICSEARCH_CA_CERT_PATH: "/etc/elasticsearch/certs/tls.crt"
  TASKS_INDEX_NAME: "devboard-tasks"
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 300m
    memory: 256Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
serviceMonitor:
  enabled: true
  interval: 15s
