replicaCount: 1
image:
  repository: ghcr.io/mitsu3s/devboard-frontend
  pullPolicy: IfNotPresent
  tag: "4db28a4c65f79a8a4a5a8b95cc9542d31667f744"
service:
  type: ClusterIP
  port: 3000
env:
  NEXT_PUBLIC_API_URL: "/api"
resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 512Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
serviceMonitor:
  enabled: false
