apiVersion: v1
kind: Service
metadata:
  name: {{ include "task-service.fullname" . }}
  labels:
    {{- include "task-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "task-service.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
